### ISSUE TITLE
Beta for Testing

### ISSUE THREAD

**Issue by ssabnis** [salyh/elastic-defender#1]
Hi

We are implementing ELK , I would like to be part of the beta test, How can I participate.

Thanks

**Comment by salyh** [comment]
You can now access the private repo and i am curious to hear about your use cases and experiences

**Comment by bcopy** [comment]
Hello,
Please grant me access too.

**Comment by zyegfryed** [comment]
Hi @salyh ,
I would really like to be part of the beta too.
Thanks in advance !

**Comment by salyh** [comment]
all added

**Comment by zyegfryed** [comment]
:cake:

**Comment by darkpixel** [comment]
February is almost over... ;)

**Comment by salyh** [comment]
@darkpixel There were a lot of interest for the beta but i much fewer feedback/contributions than expected. So its likely that i expand the beta testing phase till March. I am also visiting the elastic{on} next month and hope to meet with some people to get the roadmap clear.

**Comment by jveiga** [comment]
Hi, can I join the beta?

**Comment by salyh** [comment]
done

**Comment by darkpixel** [comment]
Awesome.  I can't wait to see it @salyh.

**Comment by awick** [comment]
Can I join the beta

**Comment by salyh** [comment]
@awick access granted

**Comment by ballesterosam** [comment]
Hi.

I would like to join the beta. Thank you!

**Comment by dforste** [comment]
Looking at the ELK stack as well. Can you get me access to the bata?

**Comment by salyh** [comment]
@ballesterosam
@dforste 

done

**Comment by ballesterosam** [comment]
Thanks!

**Comment by splitice** [comment]
Can I take a test too please :)

**Comment by salyh** [comment]
@splitice done

**Comment by arronli** [comment]
can't wait to see it !

**Comment by bradvido** [comment]
Is this intended to be a free/open alternative to Shield?
I'd like to try out your beta. I'll also be at Elastic{ON} next week, maybe we can talk more there!

**Comment by salyh** [comment]
@bradvido pls give me your e-mail address so we can schedule a meeting

**Comment by martinpinto** [comment]
Hi I am implementing a quoting system with ElasticSearch and would like access to the beta.  Please add me. Thank you in advance.

**Comment by sullb** [comment]
This looks great, can I have access please?

**Comment by salyh** [comment]
both done

**Comment by aidan-** [comment]
Hi, This project looks really interesting.  Could I please have access?

**Comment by salekseev** [comment]
I'd like to get access to the beta, please. Thanks.

**Comment by salyh** [comment]
@aidan- @salekseev done

**Comment by nekinie** [comment]
I'd like to get access to the beta, please. Thanks.

**Comment by halfninja** [comment]
@salyh could I be in the beta please? Thanks

**Comment by sokratisg** [comment]
@salyh count me in as well

**Comment by bitsofinfo** [comment]
@salyh please add me as well, thanks

**Comment by salyh** [comment]
beta closed now
